# Root project
root = "."
tmp_dir = "tmp"
testdata_dir = "testdata"

[build]
  # File .exe sau khi build
  bin = "tmp/main.exe"

  # Build đúng file main.go trong thư mục cmd
  cmd = "go build -o tmp/main.exe ./cmd/main.go"

  args_bin = []
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  enabled = false
  app_port = 0
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
