# Các thư mục air sẽ watch thay đổi để reload
watch_dir = ["cmd", "config", "internal", "pkg"]

# Các thư mục, file sẽ bỏ qua
ignore = ["tmp", "vendor"]

# Cấu hình build và chạy binary
[build]
  # Lệnh build đúng đường dẫn tới thư mục chứa main.go
  cmd = "go build -o tmp/main.exe ./cmd"

  # File binary sẽ chạy sau khi build thành công
  bin = "tmp/main.exe"
